# Generated by Django 5.2.12 on 2026-03-21 17:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScraperTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("url", models.URLField(max_length=2000)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("table", "HTML Table"),
                            ("list", "HTML List"),
                            ("form", "HTML Form"),
                            ("article", "Article Content"),
                            ("api", "JSON API"),
                            ("custom", "Custom Selector"),
                        ],
                        default="table",
                        max_length=20,
                    ),
                ),
                (
                    "css_selector",
                    models.CharField(
                        blank=True,
                        help_text="CSS selector for target element",
                        max_length=500,
                    ),
                ),
                (
                    "xpath_selector",
                    models.CharField(
                        blank=True, help_text="XPath for target element", max_length=500
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "requires_js",
                    models.BooleanField(
                        default=True,
                        help_text="Use Selenium (True) or requests (False)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="What data this target provides for testing",
                    ),
                ),
                ("last_scraped_at", models.DateTimeField(blank=True, null=True)),
                ("total_records_scraped", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "scraper_targets",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScraperRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial Success"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(null=True)),
                ("completed_at", models.DateTimeField(null=True)),
                ("records_scraped", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("triggered_by", models.CharField(default="scheduler", max_length=100)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="scraper.scrapertarget",
                    ),
                ),
            ],
            options={
                "db_table": "scraper_runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScrapedData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("raw_data", models.JSONField(help_text="Raw scraped data as JSON")),
                (
                    "normalized_data",
                    models.JSONField(
                        blank=True, help_text="Cleaned/normalized version", null=True
                    ),
                ),
                (
                    "data_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA256 hash to detect duplicates",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("raw", "Raw"),
                            ("validated", "Validated"),
                            ("used_in_tests", "Used in Tests"),
                            ("stale", "Stale"),
                        ],
                        default="raw",
                        max_length=20,
                    ),
                ),
                ("row_count", models.IntegerField(default=0)),
                ("column_count", models.IntegerField(default=0)),
                ("source_url", models.URLField(blank=True, max_length=2000)),
                (
                    "scraper_run",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scraped_records",
                        to="scraper.scraperrun",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scraped_data",
                        to="scraper.scrapertarget",
                    ),
                ),
            ],
            options={
                "db_table": "scraped_data",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["data_hash"], name="scraped_dat_data_ha_19abb6_idx"
                    ),
                    models.Index(
                        fields=["target", "status"],
                        name="scraped_dat_target__aaea46_idx",
                    ),
                ],
            },
        ),
    ]
